### ISSUE TITLE
Using Oauth2.Builder gives NoSuchMethodError for com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.<init>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#894]
```
Version of google-api-java-client (e.g. 1.15.0-rc)?
1.17.0-rc

Java environment (e.g. Java 6, Android 2.3, App Engine)?
Java 6

Describe the problem.
After Upgrading from 1.13 to 1.17 I got this issue when using the 
Oauth2.Builder to get the user info

How would you expect it to be fixed?
Is something that has to be done different in the flow? I couldn't figure what

```

Original issue reported on code.google.com by `casper...@gmail.com` on 14 Jul 2014 at 7:07

**Comment by GoogleCodeExporter** [comment]
```
Actually I get this for every service Builder.
```

Original comment by `casper...@gmail.com` on 14 Jul 2014 at 8:13

**Comment by GoogleCodeExporter** [comment]
```
Did any one fix this issue or was able to get resolve this issue ?

I have the same problem while moving from 1.15.0-rc to 1.18.0-rc.
```

Original comment by `anant.s...@aspiresoftware.in` on 11 Sep 2014 at 7:23

**Comment by GoogleCodeExporter** [comment]
```
Yes. Forgot to give the solution. Actually you have to replace all the services 
you use to have the same version.
```

Original comment by `casper...@gmail.com` on 11 Sep 2014 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
Hi, is this issue resolved already?

If not, can you give us more context so that we can reproduce? For example, a 
small snippet of how you got this exception would be helpful.
```

Original comment by `wonder...@google.com` on 22 Sep 2014 at 5:01

**Comment by GoogleCodeExporter** [comment]
Original comment by `wonder...@google.com` on 29 Oct 2014 at 10:19
- Changed state: **WontFix**
